name: Release & Publish

on:
  workflow_dispatch:
  push:
    tags:
      - v**

env:
  APP_NAME: Lark
  WORKFLOW_URL: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}

jobs:
  notify-start:
    runs-on: ubuntu-latest
    name: Report Start
    steps:
      - name: Notify Start
        uses: northwang-lucky/chatbot-webhook-client@v1.1.1
        with:
          app: ${{ env.APP_NAME }}
          webhook: ${{ secrets.CUSTOM_BOT_WEBHOOK }}
          secret: ${{ secrets.CUSTOM_BOT_SECRET }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          template: file://.template/lark-message-card.json
          params: >-
            {
              "header_color": "blue",
              "header_title": "Workflow Start",
              "repository": "${{ github.repository }}",
              "workflow": "${{ github.workflow }}",
              "workflow_url": "${{ env.WORKFLOW_URL }}"
            }
  build-test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - name: Checkout Main Branch
        uses: actions/checkout@v3
        with:
          ref: main
      - name: Set up Node 16
        if: success()
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Set up PNPM
        if: success()
        uses: pnpm/action-setup@v2
        with:
          version: 7
          run_install: false
      - name: Get PNPM Store Directory
        id: pnpm-cache
        if: success()
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT
      - name: Setup PNPM Cache
        if: success()
        uses: actions/cache@v3
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      - name: Install Dependencies
        if: success()
        run: pnpm install
      - name: Run Build and Test
        if: success()
        run: pnpm build
  release:
    runs-on: ubuntu-latest
    name: Release
    needs: build-test
    if: success()
    permissions:
      contents: write
    steps:
      - name: Release
        uses: northwang-lucky/auto-release@v0.0.3
        with:
          filepath: CHANGELOG.md
          github-token: ${{ secrets.GITHUB_TOKEN }}
  publish:
    runs-on: ubuntu-latest
    name: Publish
    needs: release
    if: success()
    steps:
      - name: Checkout Main Branch
        uses: actions/checkout@v3
        with:
          ref: main
      - name: Publish
        run: |
          npm config set //registry.npmjs.org/:_authToken ${{ secrets.NPM_TOKEN }}
          npx pnpm publish
  notify-success:
    if: success()
    runs-on: ubuntu-latest
    name: Report Success
    needs: publish
    steps:
      - name: Notify Success
        uses: northwang-lucky/chatbot-webhook-client@v1.1.1
        with:
          app: ${{ env.APP_NAME }}
          webhook: ${{ secrets.CUSTOM_BOT_WEBHOOK }}
          secret: ${{ secrets.CUSTOM_BOT_SECRET }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          template: file://.template/lark-message-card.json
          params: >-
            {
              "header_color": "green",
              "header_title": "Workflow Succeed",
              "repository": "${{ github.repository }}",
              "workflow": "${{ github.workflow }}",
              "workflow_url": "${{ env.WORKFLOW_URL }}"
            }
  notify-failure:
    if: failure()
    runs-on: ubuntu-latest
    name: Report Failure
    needs: publish
    steps:
      - name: Notify Failure
        uses: northwang-lucky/chatbot-webhook-client@v1.1.1
        with:
          app: ${{ env.APP_NAME }}
          webhook: ${{ secrets.CUSTOM_BOT_WEBHOOK }}
          secret: ${{ secrets.CUSTOM_BOT_SECRET }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          template: file://.template/lark-message-card.json
          params: >-
            {
              "header_color": "red",
              "header_title": "Workflow Failed",
              "repository": "${{ github.repository }}",
              "workflow": "${{ github.workflow }}",
              "workflow_url": "${{ env.WORKFLOW_URL }}"
            }
